#!/usr/bin/python

import argparse
import os
import re

p = re.compile(ur'.*?/([a-z]+)\.block')

parser = argparse.ArgumentParser(description='Generate BEM+Stylus files and structure.')
parser.add_argument('--b', nargs=1, required=False, help="The name of block to generate.")
parser.add_argument('--e', nargs=1, required=False, help="The name of element to generate.")
parser.add_argument('--m', nargs=1, required=False, help="The name of modifier to generate.")
parser.add_argument('--em', nargs=2, required=False, help="The name of element - modifier to generate.")
parser.add_argument('--i', required=False, help="Install the BEM stylus helper mixins.")
args = parser.parse_args()

myDir = os.path.dirname(os.path.realpath(__file__)) + '/'

if args.i:
    if os.path.exists('bem.util'):
        print 'Helpers already exist!'
        exit()
    else:
        os.makedirs('bem.util')

    rfd = os.open(myDir + 'bem.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    os.close(rfd)
    wfd = os.open('bem.util/bem.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)

if args.b:
    block = args.b[0].capitalize()
    if os.path.exists(block.lower() + '.block'):
        print 'Block already exists!'
        exit()
    else:
        os.makedirs(block.lower() + '.block/__')
        os.makedirs(block.lower() + '.block/--')

        rfd = os.open(myDir + 'blockindex.styl', os.O_RDONLY)
        content = os.read(rfd, 10000);
        content = content.replace('%BLOCK%', block.lower())
        os.close(rfd)
        wfd = os.open(block.lower() + '.block/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, content)
        os.close(wfd)

        rfd = os.open(myDir + 'block.styl', os.O_RDONLY)
        content = os.read(rfd, 10000);
        content = content.replace('%BLOCK%', block)
        os.close(rfd)
        wfd = os.open(block.lower() + '.block/' + block.lower() + '.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, content)
        os.close(wfd)

if args.e:
    element = args.e[0]
    cwd = os.getcwd()
    block = re.search(p, cwd).group(1).capitalize()

    if os.path.exists('__/index.styl') == False:
        wfd = os.open('__/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '@require "' + element + '"\n')
        os.close(wfd)
    else:
        wfd = os.open('__/index.styl', os.O_APPEND | os.O_WRONLY)
        os.write(wfd, '@require "' + element + '"\n')
        os.close(wfd)

    rfd = os.open(myDir + 'element.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    content = content.replace('%BLOCK%', block)
    content = content.replace('%ELEMENT%', element)
    os.close(rfd)
    wfd = os.open('__/' + element + '.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)

if args.m:
    modifier = args.m[0]
    cwd = os.getcwd()
    block = re.search(p, cwd).group(1).capitalize()

    if os.path.exists('--/index.styl') == False:
        wfd = os.open('--/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '@require "' + modifier + '"\n')
        os.close(wfd)
    else:
        wfd = os.open('--/index.styl', os.O_APPEND | os.O_WRONLY)
        os.write(wfd, '@require "' + modifier + '"\n')
        os.close(wfd)

    rfd = os.open(myDir + 'modifier.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    content = content.replace('%BLOCK%', block)
    content = content.replace('%MODIFIER%', modifier)
    os.close(rfd)
    wfd = os.open('--/' + modifier + '.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)

if args.em:
    element = args.em[0]
    modifier = args.em[1]
    cwd = os.getcwd()
    block = re.search(p, cwd).group(1).capitalize()

    if os.path.exists('--/index.styl') == False:
        wfd = os.open('--/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '@require "' + element + '-' + modifier + '"\n')
        os.close(wfd)
    else:
        wfd = os.open('--/index.styl', os.O_APPEND | os.O_WRONLY)
        os.write(wfd, '@require "' + element + '-' + modifier + '"\n')
        os.close(wfd)

    rfd = os.open(myDir + 'elementmodifier.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    content = content.replace('%BLOCK%', block)
    content = content.replace('%ELEMENT%', element)
    content = content.replace('%MODIFIER%', modifier)
    os.close(rfd)
    wfd = os.open('--/' + element + '-' + modifier + '.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)
