#!/usr/bin/python

import argparse
import os
import re

p = re.compile(ur'.*?/([a-z]+)\.block')

parser = argparse.ArgumentParser(description='Generate BEM+Stylus files and structure.')
parser.add_argument('--b', nargs=1, required=False, help="The name of block to generate.")
parser.add_argument('--e', nargs=1, required=False, help="The name of element to generate.")
parser.add_argument('--m', nargs=1, required=False, help="The name of modifier to generate.")
parser.add_argument('--u', nargs=1, required=False, help="The name of utility to generate.")
parser.add_argument('--em', nargs=2, required=False, help="The name of element - modifier to generate.")
parser.add_argument('--i', action='store_true', required=False, help="Install the BEM stylus helper mixins.")
args = parser.parse_args()

myDir = os.path.dirname(os.path.realpath(__file__)) + '/'

if args.i:
    if os.path.exists('bem.util'):
        print 'Helpers already exist!'
        exit()
    else:
        os.makedirs('bem.util')

    rfd = os.open(myDir + 'bem.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    os.close(rfd)
    wfd = os.open('bem.util/index.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)

    if os.path.exists('index.styl') == False:
        wfd = os.open('index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '@require "bem.util"\n')
        os.close(wfd)

if args.u:
    if os.path.exists('app.util') == False:
        os.makedirs('app.util')

    utility = args.u[0]

    rfd = os.open(myDir + 'utility.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    content = content.replace('%UTILITY%', utility)
    os.close(rfd)
    wfd = os.open('app.util/' + utility + '.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)

    if os.path.exists('app.util/index.styl') == False:
        wfd = os.open('app.util/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '@require "' + utility + '"\n')
        os.close(wfd)
    else:
        wfd = os.open('app.util/index.styl', os.O_APPEND | os.O_WRONLY)
        os.write(wfd, '@require "' + utility + '"\n')
        os.close(wfd)

if args.b:
    block = args.b[0].capitalize()
    if os.path.exists(block.lower() + '.block'):
        print 'Block already exists!'
        exit()
    else:
        os.makedirs(block.lower() + '.block/elements')
        wfd = os.open(block.lower() + '.block/elements/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '')
        os.close(wfd)

        os.makedirs(block.lower() + '.block/modifiers')
        wfd = os.open(block.lower() + '.block/modifiers/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '')
        os.close(wfd)

        rfd = os.open(myDir + 'blockindex.styl', os.O_RDONLY)
        content = os.read(rfd, 10000);
        content = content.replace('%BLOCK%', block.lower())
        os.close(rfd)
        wfd = os.open(block.lower() + '.block/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, content)
        os.close(wfd)

        rfd = os.open(myDir + 'block.styl', os.O_RDONLY)
        content = os.read(rfd, 10000);
        content = content.replace('%BLOCK%', block)
        os.close(rfd)
        wfd = os.open(block.lower() + '.block/' + block.lower() + '.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, content)
        os.close(wfd)

        if os.path.exists('index.styl') == False:
            wfd = os.open('index.styl', os.O_CREAT | os.O_WRONLY)
            os.write(wfd, '@require "' + block.lower() + '.block' + '"\n')
            os.close(wfd)
        else:
            wfd = os.open('index.styl', os.O_APPEND | os.O_WRONLY)
            os.write(wfd, '@require "' + block.lower() + '.block' + '"\n')
            os.close(wfd)

if args.e:
    element = args.e[0]
    cwd = os.getcwd()
    block = re.search(p, cwd).group(1).capitalize()

    if os.path.exists('elements/index.styl') == False:
        wfd = os.open('elements/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '@require "' + element + '"\n')
        os.close(wfd)
    else:
        wfd = os.open('elements/index.styl', os.O_APPEND | os.O_WRONLY)
        os.write(wfd, '@require "' + element + '"\n')
        os.close(wfd)

    rfd = os.open(myDir + 'element.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    content = content.replace('%BLOCK%', block)
    content = content.replace('%ELEMENT%', element)
    os.close(rfd)
    wfd = os.open('elements/' + element + '.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)

if args.m:
    modifier = args.m[0]
    cwd = os.getcwd()
    block = re.search(p, cwd).group(1).capitalize()

    if os.path.exists('modifiers/index.styl') == False:
        wfd = os.open('modifiers/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '@require "' + modifier + '"\n')
        os.close(wfd)
    else:
        wfd = os.open('modifiers/index.styl', os.O_APPEND | os.O_WRONLY)
        os.write(wfd, '@require "' + modifier + '"\n')
        os.close(wfd)

    rfd = os.open(myDir + 'modifier.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    content = content.replace('%BLOCK%', block)
    content = content.replace('%MODIFIER%', modifier)
    os.close(rfd)
    wfd = os.open('modifiers/' + modifier + '.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)

if args.em:
    element = args.em[0]
    modifier = args.em[1]
    cwd = os.getcwd()
    block = re.search(p, cwd).group(1).capitalize()

    if os.path.exists('modifiers/index.styl') == False:
        wfd = os.open('modifiers/index.styl', os.O_CREAT | os.O_WRONLY)
        os.write(wfd, '@require "' + element + '-' + modifier + '"\n')
        os.close(wfd)
    else:
        wfd = os.open('modifiers/index.styl', os.O_APPEND | os.O_WRONLY)
        os.write(wfd, '@require "' + element + '-' + modifier + '"\n')
        os.close(wfd)

    rfd = os.open(myDir + 'elementmodifier.styl', os.O_RDONLY)
    content = os.read(rfd, 10000);
    content = content.replace('%BLOCK%', block)
    content = content.replace('%ELEMENT%', element)
    content = content.replace('%MODIFIER%', modifier)
    os.close(rfd)
    wfd = os.open('modifiers/' + element + '-' + modifier + '.styl', os.O_CREAT | os.O_WRONLY)
    os.write(wfd, content)
    os.close(wfd)
